### Evaluating loss, gradients and related objects

TATi gives you immediate access to all important properties of the neural network in a straight-forward manner.

In [1]:
import TATi.simulation as tati

Let us instantiate a perceptron, add the dataset we have seen before and take a look.

In [7]:
nn = tati(batch_data_files=["dataset-twoclusters.csv"],
          batch_data_file_type="csv",
          do_hessians=True,
          hidden_dimension=[0],
          hidden_activation="linear", output_activation="relu",
          loss="mean_squared",
          seed=426)

#### Parameters

$\Theta = (W,B) = (W_1, \ldots, W_L, B_1, \ldots, B_L)$

In [8]:
print(nn.parameters)

[0.32344854, 0.2837119, 0.1]


Modify parameters by simply setting them.

In [9]:
import numpy as np
nn.parameters = np.array([0.1, 0.1, 0.1], dtype=np.float32)
print(nn.parameters)

[0.1, 0.1, 0.1]


#### Loss

$L_D (\Theta)$

In [10]:
print(nn.loss())

0.62180895


#### Gradients

$\nabla_{\Theta} L_D(\Theta)$

In [11]:
print(nn.gradients())

[-0.8407791  -1.1261038  -0.48922905]


#### Hessian

$H_{i,j} = \partial_{\Theta_i} \partial_{\Theta_j} L_D(\Theta)$

In [12]:
print(nn.hessians())

[[3.4066586 4.129916  1.7715963]
 [4.1299157 5.6340656 2.3361132]
 [1.7715963 2.3361132 1.       ]]


> Hessians are very expensive as they incur ${\cal O}(N^2)$ cost if $N$ is the number of degrees of freedom of the network. Hence, they have to be activated deliberately as also the associated node's creation scales by this complexity.

### Summary

- how to access parameter, loss, gradients, hessians